lang = {
    title : "RI-SERIE",
    first_tab : "HEIM",
    second_tab : "TRACE",
    third_tab : "PARAMETER",
    scan_button : "GERÄTE-SCAN",
    end_button : "SITZUNG BEENDEN",
    send_button : "SCHICKEN",
    clear_button : "KLAR",
    trace_button1 : "TRACE AUS",
    trace_button2 : "TRACE AN",
    update_button : "UPDATE",
    data_log_label : "DATENPROTOKOLL",
    parameter_label: "LIVE-PARAMETER",
    level_label: "FÜLLSTAND:",
    distance_label : "ABSTAND:",
    status_label : "STATUS:",
    command_box_label : "BEFEHLSKASTEN",
    bluetooth_parameters_label : "BLUETOOTH-PARAMETER",
    range_label : "BEREICH &nbsp [",
    device_name_label : "NAME DES GERÄTS",
    pin_number_label : "PIN NUMMER",
    radar_parameters_label : "RADARPARAMETER",
    indicator_mode_label : "ANZEIGEMODUS (P241)",
    measurement_mode_label : "MESSMODUS (P100)",
    measurement_units_label : "MESSEINHEITEN (P104)",
    empty_distance_label : "LEERER ABSTAND (P105)",
    span_label : "SPANNE (P106)",
    fail_mode_label : "FEHLERMODUS (P808)",
    volume_units_label : "EINHEIT DES VOLUMENS (P605)",
    p21_label : "ABSTAND EINSTELLEN (P21)",
    p241_dropdown_0: "Wählen P241",
    p241_dropdown_1: "0 = AUS",
    p241_dropdown_2: "1 = Inst. Flüssig",
    p241_dropdown_3: "2 = Inst. Solide",
    // p241_dropdown_4: "3 = Inst. Flüssig",
    p241_dropdown_5: "4 = Mess. Flüssig",
    p241_dropdown_6: "5 = Mess. Solide",
    // p241_dropdown_7: "6 = Mess. Solide",
    p241_dropdown_8: "7 = Gesundheit",
    p100_dropdown_0: "Wählen P100",
    p100_dropdown_1: "1 = Abstand",
    p100_dropdown_2: "2 = Füllstand",
    p100_dropdown_3: "3 = Leerraum",
    p100_dropdown_4: "4 = Volumen",
    p104_dropdown_0: "Wählen P104",
    p104_dropdown_1: "1 = m",
    p104_dropdown_2: "2 = cm",
    p104_dropdown_3: "3 = mm",
    p104_dropdown_4: "4 = ft",
    p104_dropdown_5: "5 = ins",
    p808_dropdown_0: "Wählen P808",
    p808_dropdown_1: "1 = Halten",
    p808_dropdown_2: "2 = Max.",
    p808_dropdown_3: "3 = Min.",
    p808_dropdown_4: "4 = 22mA",
    p808_dropdown_5: "5 = 3.8mA",
    p605_dropdown_0: "Wählen P605",
    p605_dropdown_1: "0 = Keiner",
    p605_dropdown_2: "1 = Tonnen",
    p605_dropdown_3: "2 = LongTons",
    p605_dropdown_4: "3 = m³",
    p605_dropdown_5: "4 = Liter",
    p605_dropdown_6: "5 = Imperial Gal",
    p605_dropdown_7: "6 = US Gal",
    p605_dropdown_8: "7 = ft³",
    p605_dropdown_9: "8 = Barrel",
    log_message1 : "Gerät nicht im Normalmodus!",
    log_message2 : "Kein Gerät verbunden!",
    log_message3 : " → Ungültige Parameteranforderung",
    log_message4 : " ← Einloggen erfolgreich",
    log_message5 : " ← Normalmodus fehlgeschlagen",
    log_message6 : " ← In Verbindung gebracht",
    log_message7 : " ← Trennen",
    log_message8 : " → Bluetooth-Verbindung beendet!",
    log_message9 : " → Getrennt",
    log_message10 : " → Bluetooth-Gerät ist bereits getrennt",
    log_message11 : " → Trennen",
    log_message12 : " → Protokollierung ...",
    log_message13 : " → Trennen ...",
    log_message14 : " → Verbinden ...",
    log_message15 : "Fehlgeschlagen: ",
    log_message16 : "Anfordern eines Bluetooth-Geräts...",
    log_message17 : "Name: ",
    log_message18 : "Bereit zu kommunizieren!\n",
    log_message19 : " → Überprüfen des Bluetooth-Leistungspegels",
    log_message20 : " → Befehl senden. Warten Sie mal...",
    log_message21 : "Klicken Sie zum Scannen auf 'Geräte-scan'",
    alert_message1 : "Warnung: Anzeige (P241) ist auf Installationsmodus eingestellt. Wechseln Sie nach der Installation in den Gesundheitsmodus (P241 = 7)!",
    alert_message2 : "Passwörter stimmen nicht überein!",
    alert_message3 : "Gerätename ist leer!",
    alert_message4 : "Der Gerätename darf maximal 4 alphanumerische Zeichen lang sein!",
    alert_message5 : "Passwort ist leer",
    alert_message6 : "Das Passwort darf maximal 6 Ziffern enthalten!",
    alert_message7 : "Passwort darf nur Ziffern enthalten!",
    status1 : "OK",
    status2 : "LOE hoch scheitern",
    status3 : "LOE niedrig scheitern",
    status4 : "LOE scheitern",
    status5 : "LOE",
    status6 : "Temp",
    status7 : "Stromspannung",
    status8 : "Alarm",
    volume_string : "Volumen\t= ",
    temp_string : "Temp\t= ",
    output_string : "Ausgang\t= ",
    command_box_placeholder : "Geben Sie den Befehl ein",
    top_message1 : "Erfassung von Trace-Daten. Warten Sie mal...",
    top_message2 : "P241 abfragen. Warten Sie mal...",
    top_message3 : "P100 abfragen. Warten Sie mal...",
    top_message4 : "P104 abfragen. Warten Sie mal...",
    top_message5 : "P105 abfragen. Warten Sie mal...",
    top_message6 : "P106 abfragen. Warten Sie mal...",
    top_message7 : "P808 abfragen. Warten Sie mal...",
    top_message8 : "P605 abfragen. Warten Sie mal...",
    top_message9 : "P21 abfragen. Warten Sie mal...",
    top_message10 : "Erfassen von ECHO-Daten. Warten Sie mal...",
    top_message11 : "Erfassen von DATEM-Daten. Warten Sie mal...",
    top_message12 : "Neues Bluetooth-Passwort festlegen. Warten Sie mal...",
    top_message13 : "Erfassen von RADAR-Parametern. Warten Sie mal...",
    top_message14 : "Aktualisieren von P241. Warten Sie mal...",
    top_message15 : "Aktualisieren von P100. Warten Sie mal...",
    top_message16 : "Aktualisieren von P104. Warten Sie mal...",
    top_message17 : "Aktualisieren von P105. Warten Sie mal...",
    top_message18 : "Aktualisieren von P106. Warten Sie mal...",
    top_message19 : "Aktualisieren von P808. Warten Sie mal...",
    top_message20 : "Aktualisieren von P605. Warten Sie mal...",
    top_message21 : "Aktualisieren von P21. Warten Sie mal...",
    login_message1 : "Fehler bei der Anmeldung",
    p605_unit1 : "m³",
    p605_unit2 : "Keiner",
    p605_unit3 : "Tonnen",
    p605_unit4 : "LongTons",
    p605_unit5 : "Liter",
    p605_unit6 : "Imp Gal",
    p605_unit7 : "US Gal",
    p605_unit8 : "ft³",
    p605_unit9 : "Barrel",
    reconfirm_pwd_title : "PASSWORT ERNEUT BESTÄTIGEN",
    reconfirm_pwd_msg1 : "Bitte bestätigen Sie das Passwort erneut: &nbsp",
    reconfirm_pwd_msg2 : "Bitte notieren Sie sich das Passwort zur sicheren Aufbewahrung",
};
