lang = {
    title : "RI-SERIE",
    first_tab : "START",
    second_tab : "DIAGNOSE",
    third_tab : "PARAMETER",
    scan_button : "SUCHE SENSOR",
    end_button : "END SESSION",
    send_button : "SENDEN",
    clear_button : "LÖSCHEN",
    trace_button1 : "DIAGNOSE AUS",
    trace_button2 : "DIAGNOSE EIN",
    update_button : "UPDATE",
    data_log_label : "DATA LOG",
    parameter_label: "AKTUELLE MESSWERTE",
    level_label: "FÜLLSTAND:",
    distance_label : "ABSTAND:",
    status_label : "STATUS:",
    command_box_label : "COMMAND BOX",
    bluetooth_parameters_label : "BLUETOOTH PARAMETER",
    range_label : "RANGE &nbsp [",
    device_name_label : "SENSOR NAME",
    pin_number_label : "PIN NUMMER",
    radar_parameters_label : "RADAR PARAMETER",
    indicator_mode_label : "LED ANZEIGE MODUS (P241)",
    measurement_mode_label : "BETRIEBSMODUS (P100)",
    measurement_units_label : "EINHEITEN (P104)",
    empty_distance_label : "NULLPUNKT (P105)",
    span_label : "MESSSPANNE (P106)",
    fail_mode_label : "FEHLER MODUS (P808)",
    volume_units_label : "EINHEIT DES VOLUMENS (P605)",
    p21_label : "EINGABE ABSTAND (P21)",
    p241_dropdown_0: "Wähle P241",
    p241_dropdown_1: "0 = AUS",
    p241_dropdown_2: "1 = Installation FLÜSSIGKEIT",
    p241_dropdown_3: "2 = Installation SCHÜTTGUT",
    // p241_dropdown_4: "3 = Installation FLÜSSIGKEIT",
    p241_dropdown_5: "4 = Messung FLÜSSIGKEIT",
    p241_dropdown_6: "5 = Messung SCHÜTTGUT",
    // p241_dropdown_7: "6 = Messung SCHÜTTGUT",
    p241_dropdown_8: "7 = Selbstdiagnose",
    p100_dropdown_0: "Wähle P100",
    p100_dropdown_1: "1 = Abstand",
    p100_dropdown_2: "2 = Füllstand",
    p100_dropdown_3: "3 = Leerraum",
    p100_dropdown_4: "4 = Volumen",
    p104_dropdown_0: "Wähle P104",
    p104_dropdown_1: "1 = m",
    p104_dropdown_2: "2 = cm",
    p104_dropdown_3: "3 = mm",
    p104_dropdown_4: "4 = ft",
    p104_dropdown_5: "5 = ins",
    p808_dropdown_0: "Wähle P808",
    p808_dropdown_1: "1 = Wert halten",
    p808_dropdown_2: "2 = Max.",
    p808_dropdown_3: "3 = Min.",
    p808_dropdown_4: "4 = 22 mA",
    p808_dropdown_5: "5 = 3.8 mA",
    p605_dropdown_0: "Wähle P605",
    p605_dropdown_1: "0 = Ohne Inhalt",
    p605_dropdown_2: "1 = Tonnen",
    p605_dropdown_3: "2 = Long Ton",
    p605_dropdown_4: "3 = m³",
    p605_dropdown_5: "4 = Liter",
    p605_dropdown_6: "5 = Brit. Gal",
    p605_dropdown_7: "6 = US Gal",
    p605_dropdown_8: "7 = ft³",
    p605_dropdown_9: "8 = Barrels",
    log_message1 : "Sensor nicht im normalen Modus!",
    log_message2 : "Kein Sensor verbunden!",
    log_message3 : " → Ungültige Param. Eingabe",
    log_message4 : " ← Log in erfolgreich",
    log_message5 : " ← Normaler Modus fehlgeschlagen",
    log_message6 : " ← Verbunden",
    log_message7 : " ← Getrennt",
    log_message8 : " → Bluetooth Verbindung beendet!",
    log_message9 : " → Getrennt",
    log_message10 : " → Bluetooth Gerät ist bereits getrennt",
    log_message11 : " → Getrennt",
    log_message12 : " → Logging ...",
    log_message13 : " → Getrennt ...",
    log_message14 : " → Verbunden ...",
    log_message15 : "Fehlgeschlagen: ",
    log_message16 : "Abfrage Bluetooth Gerät...",
    log_message17 : "Name: ",
    log_message18 : "Bereit zu kommunizieren!\n",
    log_message19 : " → Prüfe Bluetooth Leistungsstufe",
    log_message20 : " → Sende Kommando. Bitte warten...",
    log_message21 : "Klicke auf 'Suche Sensor' um zu scannen",
    alert_message1 : "Warnung: LED Anzeige (P241) befindet sich im Installationsmodus. Schalte auf Selbstdiagnose (P241 = 7) nach der Installation!",
    alert_message2 : "Passwörter stimmen nicht überein!",
    alert_message3 : "Sensor Name ist leer!",
    alert_message4 : "Sensor Name max. Länge 4 Alphanumerische Zeichen!",
    alert_message5 : "Passwort ist leer",
    alert_message6 : "Passwort max. Länge 6 Nummern!",
    alert_message7 : "Das Passwort darf nur Nummern enthalten!",
    status1 : "OK",
    status2 : "Echoverlust high",
    status3 : "Echoverlust low",
    status4 : "Echoverlust fail",
    status5 : "Echoverlust",
    status6 : "Temperatur",
    status7 : "Spannung",
    status8 : "Alarm",
    volume_string : "Volume\t= ",
    temp_string : "Temp\t= ",
    output_string : "Output\t= ",
    command_box_placeholder : "Enter the command",
    top_message1 : "Acquiring trace data. Please wait...",
    top_message2 : "Abfrage P241. Bitte Warten...",
    top_message3 : "Abfrage P100. Bitte Warten...",
    top_message4 : "Abfrage P104. Bitte Warten...",
    top_message5 : "Abfrage P105. Bitte Warten...",
    top_message6 : "Abfrage P106. Bitte Warten...",
    top_message7 : "Abfrage P808. Bitte Warten...",
    top_message8 : "Abfrage P605. Bitte Warten...",
    top_message9 : "Abfrage P21. Bitte Warten...",
    top_message10 : "Empfange ECHO Daten. Bitte Warten...",
    top_message11 : "Empfange DATEM Informationen Bitte Warten...",
    top_message12 : "Neues Bluetooth-Passwort festlegen. Bitte Warten...",
    top_message13 : "Empfange RADAR Parameter. Bitte Warten...",
    top_message14 : "Update P241. Bitte Warten...",
    top_message15 : "Update P100. Bitte Warten...",
    top_message16 : "Update P104. Bitte Warten...",
    top_message17 : "Update P105. Bitte Warten...",
    top_message18 : "Update P106. Bitte Warten...",
    top_message19 : "Update P808. Bitte Warten...",
    top_message20 : "Update P605. Bitte Warten...",
    top_message21 : "Update P21. Bitte Warten...",
    login_message1 : "Login fehlgeschlagen",
    p605_unit1 : "m³",
    p605_unit2 : "Ohne Inhalt",
    p605_unit3 : "Tonnen",
    p605_unit4 : "long Tons",
    p605_unit5 : "Liter",
    p605_unit6 : "Imp Gal",
    p605_unit7 : "US Gal",
    p605_unit8 : "ft³",
    p605_unit9 : "Barrels",
    reconfirm_pwd_title : "PASSWORT ERNEUT BESTÄTIGEN",
    reconfirm_pwd_msg1: "BITTE PASSWORT ERNEUT BESTÄTIGEN: &nbsp &nbsp",
    reconfirm_pwd_msg2 : "Bitte notieren Sie das Passwort an einem sicheren Ort",
    language_label : "SPRACHE",
    language_dropdown_0: "Wähle Sprache",
    language_dropdown_1: "Englisch",
    language_dropdown_2: "Deutsch",

};