lang = {
    title : "RI-SERIES",
    first_tab : "HOME",
    second_tab : "TRACE",
    third_tab : "SETTINGS",
    scan_button : "DEVICE SCAN",
    end_button : "END SESSION",
    send_button : "SEND",
    clear_button : "CLEAR",
    trace_button1 : "TRACE OFF",
    trace_button2 : "TRACE ON",
    update_button : "UPDATE",
    data_log_label : "DATA LOG",
    parameter_label: "LIVE PARAMETERS",
    level_label: "LEVEL:",
    distance_label : "DISTANCE:",
    status_label : "STATUS:",
    command_box_label : "COMMAND BOX",
    bluetooth_parameters_label : "BLUETOOTH PARAMETERS",
    range_label : "RANGE &nbsp [",
    device_name_label : "DEVICE NAME",
    pin_number_label : "PIN NUMBER",
    radar_parameters_label : "RADAR PARAMETERS",
    indicator_mode_label : "INDICATOR MODE (P241)",
    measurement_mode_label : "MEASUREMENT MODE (P100)",
    measurement_units_label : "MEASUREMENT UNITS (P104)",
    empty_distance_label : "EMPTY DISTANCE (P105)",
    span_label : "SPAN (P106)",
    fail_mode_label : "FAIL MODE (P808)",
    volume_units_label : "VOLUME UNITS (P605)",
    p21_label : "SET DISTANCE (P21)",
    p241_dropdown_0: "Choose P241",
    p241_dropdown_1: "0 = OFF",
    p241_dropdown_2: "1 = Inst. Liquid",
    p241_dropdown_3: "2 = Inst. Solid",
    // p241_dropdown_4: "3 = Inst. Liquid",
    p241_dropdown_5: "4 = Meas. Liquid",
    p241_dropdown_6: "5 = Meas. Solid",
    // p241_dropdown_7: "6 = Meas. Solid",
    p241_dropdown_8: "7 = Health",
    p100_dropdown_0: "Choose P100",
    p100_dropdown_1: "1 = Distance",
    p100_dropdown_2: "2 = Level",
    p100_dropdown_3: "3 = Space",
    p100_dropdown_4: "4 = Volume",
    p104_dropdown_0: "Choose P104",
    p104_dropdown_1: "1 = m",
    p104_dropdown_2: "2 = cm",
    p104_dropdown_3: "3 = mm",
    p104_dropdown_4: "4 = ft",
    p104_dropdown_5: "5 = ins",
    p808_dropdown_0: "Choose P808",
    p808_dropdown_1: "1 = Hold",
    p808_dropdown_2: "2 = High",
    p808_dropdown_3: "3 = Low",
    p808_dropdown_4: "4 = 22mA",
    p808_dropdown_5: "5 = 3.8mA",
    p605_dropdown_0: "Choose P605",
    p605_dropdown_1: "0 = None",
    p605_dropdown_2: "1 = Tons",
    p605_dropdown_3: "2 = Tonnes",
    p605_dropdown_4: "3 = m³",
    p605_dropdown_5: "4 = Litres",
    p605_dropdown_6: "5 = Imperial Gal",
    p605_dropdown_7: "6 = US Gal",
    p605_dropdown_8: "7 = ft³",
    p605_dropdown_9: "8 = Barrels",
    log_message1 : "Device not in Normal mode!",
    log_message2 : "No device connected!",
    log_message3 : " → Invalid param request",
    log_message4 : " ← Log in Success",
    log_message5 : " ← Normal mode failed",
    log_message6 : " ← Connected",
    log_message7 : " ← Disconnecting",
    log_message8 : " → Bluetooth connection terminated!",
    log_message9 : " → Disconnected",
    log_message10 : " → Bluetooth Device is already disconnected",
    log_message11 : " → Disconnecting",
    log_message12 : " → Logging ...",
    log_message13 : " → Disconnecting ...",
    log_message14 : " → Connecting ...",
    log_message15 : "Failed: ",
    log_message16 : "Requesting Bluetooth Device...",
    log_message17 : "Name: ",
    log_message18 : "Ready to communicate!\n",
    log_message19 : " → Checking bluetooth power level",
    log_message20 : " → Sending command. Please wait...",
    log_message21 : "Click on 'Device scan' to scan",
    alert_message1 : "Warning: Indicator (P241) is set to installation mode. Switch to Health mode (P241 = 7) after installation!",
    alert_message2 : "Passwords do not match!",
    alert_message3 : "Device Name is empty!",
    alert_message4 : "Device Name can only have a maximum of 4 alphanumeric characters!",
    alert_message5 : "Password is empty",
    alert_message6 : "Password can only have a maximum of 6 numeric characters!",
    alert_message7 : "Password should only contain numeric characters!",
    status1 : "OK",
    status2 : "LOE fail high",
    status3 : "LOE fail low",
    status4 : "LOE fail",
    status5 : "LOE",
    status6 : "Temp",
    status7 : "Voltage",
    status8 : "Alarm",
    volume_string : "Volume\t= ",
    temp_string : "Temp\t= ",
    output_string : "Output\t= ",
    command_box_placeholder : "Enter the command",
    top_message1 : "Acquiring trace data. Please wait...",
    top_message2 : "Querying P241. Please wait...",
    top_message3 : "Querying P100. Please wait...",
    top_message4 : "Querying P104. Please wait...",
    top_message5 : "Querying P105. Please wait...",
    top_message6 : "Querying P106. Please wait...",
    top_message7 : "Querying P808. Please wait...",
    top_message8 : "Querying P605. Please wait...",
    top_message9 : "Querying P21. Please wait...",
    top_message10 : "Acquiring ECHO data. Please wait...",
    top_message11 : "Acquiring DATEM data. Please wait...",
    top_message12 : "Setting new Bluetooth password. Please wait...",
    top_message13 : "Acquiring RADAR Parameters. Please wait...",
    top_message14 : "Updating P241. Please wait...",
    top_message15 : "Updating P100. Please wait...",
    top_message16 : "Updating P104. Please wait...",
    top_message17 : "Updating P105. Please wait...",
    top_message18 : "Updating P106. Please wait...",
    top_message19 : "Updating P808. Please wait...",
    top_message20 : "Updating P605. Please wait...",
    top_message21 : "Updating P21. Please wait...",
    login_message1 : "Login failed",
    p605_unit1 : "m³",
    p605_unit2 : "None",
    p605_unit3 : "Tons",
    p605_unit4 : "Tonnes",
    p605_unit5 : "Litres",
    p605_unit6 : "Imp Gal",
    p605_unit7 : "US Gal",
    p605_unit8 : "ft³",
    p605_unit9 : "Barrels",
    reconfirm_pwd_title : "RECONFIRM PASSWORD",
    reconfirm_pwd_msg1: "Please reconfirm the password: &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp",
    reconfirm_pwd_msg2 : "Kindly note down password for safekeeping",
};
